name: Workshop Automation

on:
  push:
    branches:
      - main # Или ваша основная ветка

jobs:
  generate_token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate_token.outputs.token }}
    steps:
      - name: Generate GitHub Token
        id: generate_token
        run: |
          echo "token=$(echo ${{ secrets.GITHUB_TOKEN }})" >> $GITHUB_OUTPUT

  update_html:
    runs-on: ubuntu-latest
    needs: generate_token
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update index.html with token
        run: |
          sed -i "s/\${{ secrets.GITHUB_TOKEN }}/${{ needs.generate_token.outputs.token }}/g" index.html

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Update index.html with GitHub token" || echo "No changes to commit"
          git push origin main || echo "No changes to push"